- name: Change SSH Port to Non-Default
  hosts: all
  become: true
  vars_files:
    - ../vars.yml
  tasks:
    - name: Change port
      register: sshd_config
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^Port "
        line: "Port {{ port }}"
    - name: Restart ssh
      systemd:
        name: ssh
        enabled: true
        state: restarted
      when: sshd_config is changed