- name: Install Docker
  hosts: all
  become: true
  vars:
    deb_arch:
      "armv6l": "armhf"
      "armv7l": "armhf"
      "aarch64": "arm64"
      "x86_64": "amd64"
      "i386": "i386"
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ deb_arch[ansible_architecture] }}] https://download.docker.com/linux/{{ ansible_distribution | lower }}
          {{ ansible_lsb.codename }} stable
        state: present
        filename: docker

    - name: Update package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker and dependencies
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
        groups: docker
        append: yes

    - name: Ensure Docker is started and enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
