- name: Install Portainer
  tasks:
    - name: Create Portainer volume
      docker_volume:
        name: "{{ portainer_volume_name }}"
        state: present
    - name: Run Portainer container
      docker_container:
        name: "{{ portainer_name }}"
        image: "{{ portainer_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ portainer_external_port }}:9000"
        volumes:
          - "{{ portainer_volume_name }}:/data"
          - /var/run/docker.sock:/var/run/docker.sock